backend:
  name: github
  repo: instea/netlify-cms-poc
  branch: master
  base_url: http://localhost:3000
publish_mode: editorial_workflow
media_folder: src/content/media
collections:
  - name: "main"
    label: "Application configuration"
    files:
      - name: "General information"
        label: "Application information"
        delete: false
        file: "src/content/general.json"
        fields:
          - name: "appTitle"
            label: "Title"
            widget: "string"
            required: true
          - name: "crossTrack"
            label: "Cross track"
            widget: "object"
            fields:
              - name: "color"
                label: "Color"
                widget: "color"
                required: true
              - name: "label"
                label: "Label"
                widget: "string"
                required: true
              - name: "cardBackgroundColor"
                label: "Card background color"
                widget: "color"
                required: true
      - name: "navigation"
        label: "Navigation"
        delete: false
        file: "src/content/navigation.json"
        fields:
          - name: "location"
            label: "Location"
            widget: "object"
            fields:
              - name: "about"
                label: "About"
                widget: "string"
                required: true
              - name: "program"
                label: "Program"
                widget: "string"
                required: true
              - name: "venue"
                label: "Venue"
                widget: "string"
                required: true
              - name: "sponsors"
                label: "Sponsors"
                widget: "string"
                required: true
              - name: "chat"
                label: "Chat"
                widget: "string"
                required: true
              - name: "reportProblem"
                label: "Report problem"
                widget: "string"
                required: true
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "src/content/about.json"
        delete: false
        fields:
          - name: "text"
            label: "Text"
            widget: "markdown"
            required: true